
import React, { useState, useEffect } from 'react';
import { Tool, TeaserScenario } from '../types';
import Button from './Button';
import { X, Copy, Check, Sparkles, ExternalLink, Terminal, Eye, EyeOff, Cpu, Download, Mail } from 'lucide-react';

interface TeaserModalProps {
  tool: Tool | null;
  onClose: () => void;
}

const TeaserModal: React.FC<TeaserModalProps> = ({ tool, onClose }) => {
  const [input, setInput] = useState('');
  const [response, setResponse] = useState('');
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [showSystemPrompt, setShowSystemPrompt] = useState(false);
  
  // Download / Email Gate State
  const [email, setEmail] = useState('');
  const [isRegistered, setIsRegistered] = useState(false);
  const [isSubmittingEmail, setIsSubmittingEmail] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);

  // Reset state when tool changes
  useEffect(() => {
    setInput('');
    setResponse('');
    setLoading(false);
    setShowSystemPrompt(false);
    setEmail('');
    setIsRegistered(false);
    setIsSubmittingEmail(false);
    setIsDownloading(false);
  }, [tool]);

  if (!tool) return null;

  const runSimulation = (scenario: TeaserScenario) => {
    setInput(scenario.input);
    setResponse('');
    setLoading(true);
    
    // Simulate network latency for realism
    setTimeout(() => {
      setLoading(false);
      setResponse(scenario.output);
    }, 1500);
  };

  const copyPrompt = () => {
    const fullPrompt = `System Role: ${tool.systemPromptTeaser}\n\nUser Task: ${input}`;
    navigator.clipboard.writeText(fullPrompt);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleEmailSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!email) return;
    
    setIsSubmittingEmail(true);
    // Simulate API call to register email
    setTimeout(() => {
      setIsRegistered(true);
      setIsSubmittingEmail(false);
    }, 1000);
  };

  // Robust download handler
  const handleDownload = async () => {
    if (!tool.demoFilePath) return;
    setIsDownloading(true);

    // Helper to generate fallback content
    const generateFallback = () => {
      return `# ${tool.name} - DEMO SPECIFICATION\n` +
             `**Generated by AEstruct Inc.**\n\n` +
             `## System Prompt Teaser\n` +
             `${tool.systemPromptTeaser}\n\n` +
             `## Tool Description\n` +
             `${tool.description}\n\n` +
             `## Core Features\n` +
             tool.features.map(f => `- ${f}`).join('\n') + `\n\n` +
             `---\n` +
             `*Note: This file was auto-generated for demonstration purposes.*`;
    };

    const triggerDownload = (content: string) => {
      const blob = new Blob([content], { type: 'text/markdown' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${tool.id}-demo.md`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    };

    try {
      // Try the path exactly as defined (relative)
      let fetchUrl = tool.demoFilePath;
      console.log(`Attempting download from: ${fetchUrl}`);
      
      let response = await fetch(fetchUrl);
      
      // If failed, try prepending 'public/' (common in some dev servers)
      if (!response.ok) {
         console.log(`First attempt failed. Retrying with 'public/${fetchUrl}'`);
         response = await fetch(`public/${fetchUrl}`);
      }
      
      // If failed, try absolute path (common in production roots)
      if (!response.ok) {
         console.log(`Second attempt failed. Retrying with '/${fetchUrl}'`);
         response = await fetch(`/${fetchUrl}`);
      }

      // Check Content-Type to ensure we didn't get a 404 HTML page
      const contentType = response.headers.get("content-type");
      const isHtml = contentType && contentType.includes("text/html");

      if (response.ok && !isHtml) {
        // Success: We found the real file
        const content = await response.text();
        triggerDownload(content);
      } else {
        // Failure: File missing from build or path incorrect
        console.warn("Real demo file not found. Generating fallback content.");
        const content = generateFallback();
        triggerDownload(content);
      }
      
    } catch (error) {
      console.error("Download failed completely", error);
      // Last resort fallback
      const content = generateFallback();
      triggerDownload(content);
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-0 sm:p-4 bg-black/90 backdrop-blur-md animate-in fade-in duration-200">
      <div className="bg-ae-card w-full max-w-6xl rounded-none sm:rounded-2xl border-x-0 sm:border border-ae-accent/30 shadow-2xl flex flex-col h-full sm:h-auto sm:max-h-[90vh] overflow-hidden">
        
        {/* Header */}
        <div className="p-4 md:p-6 border-b border-white/10 flex justify-between items-center bg-ae-darker flex-shrink-0">
          <div>
            <h2 className="text-xl md:text-2xl font-serif text-ae-light flex items-center gap-2 md:gap-3">
              <div className="p-2 bg-ae-accent/10 rounded-lg text-ae-accent">
                <Sparkles className="w-5 h-5" />
              </div>
              <span className="truncate max-w-[200px] sm:max-w-none">{tool.name}</span>
            </h2>
            <div className="flex items-center gap-2 mt-2">
              <span className="px-2 py-0.5 rounded bg-ae-accent text-ae-darker text-[10px] font-bold uppercase tracking-wide">
                Simulation Mode
              </span>
              <p className="text-ae-muted text-xs font-mono hidden sm:block">v3.0 // System Logic Preview</p>
            </div>
          </div>
          <button onClick={onClose} className="text-ae-muted hover:text-white transition-colors p-2 hover:bg-white/5 rounded-full">
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Body */}
        <div className="flex-grow overflow-y-auto bg-ae-dark flex flex-col md:flex-row">
          
          {/* Left Panel: Scenarios & Download */}
          <div className="w-full md:w-[350px] lg:w-[400px] p-4 md:p-6 border-b md:border-b-0 md:border-r border-white/10 bg-ae-darker/50 flex flex-col flex-shrink-0">
             
             {/* Scenarios Section */}
             <div className="mb-6 flex-shrink-0">
               <h3 className="text-xs font-bold text-ae-muted uppercase tracking-wider mb-2 flex items-center gap-2">
                 <Terminal className="w-4 h-4" /> Test Scenarios
               </h3>
               <p className="text-xs text-ae-muted leading-relaxed mb-4 hidden md:block">
                 Select a pre-configured test case to observe how our proprietary system prompts analyze and structure complex data.
               </p>
               
               {/* Mobile: Horizontal Scroll | Desktop: Vertical Stack */}
               <div className="flex md:flex-col gap-3 overflow-x-auto md:overflow-visible pb-2 md:pb-0 -mx-4 px-4 md:mx-0 md:px-0 snap-x hide-scrollbar">
                 {tool.scenarios?.map((scenario) => (
                   <button
                     key={scenario.id}
                     onClick={() => runSimulation(scenario)}
                     disabled={loading}
                     className="min-w-[280px] md:min-w-0 snap-center w-full text-left p-4 rounded-lg border border-white/10 hover:border-ae-accent/50 hover:bg-white/5 transition-all group relative overflow-hidden flex-shrink-0"
                   >
                     <div className="relative z-10">
                       <div className="font-bold text-ae-light text-sm group-hover:text-ae-accent transition-colors flex items-center justify-between">
                         {scenario.label}
                         <ArrowIcon className="opacity-0 group-hover:opacity-100 transition-opacity transform -rotate-90 w-3 h-3" />
                       </div>
                       <div className="text-xs text-ae-muted truncate mt-1 opacity-70 font-mono">
                         {scenario.input.substring(0, 40)}...
                       </div>
                     </div>
                     {loading && input === scenario.input && (
                       <div className="absolute inset-0 bg-ae-accent/5 animate-pulse"></div>
                     )}
                   </button>
                 ))}
               </div>
             </div>

             {/* Download Section (Pushed to bottom on desktop, flows naturally on mobile) */}
             <div className="md:mt-auto pt-6 border-t border-white/10">
               <h3 className="text-xs font-bold text-ae-muted uppercase tracking-wider mb-3 flex items-center gap-2">
                 <Download className="w-4 h-4" /> Download Full Demo
               </h3>
               
               {!isRegistered ? (
                 <form onSubmit={handleEmailSubmit} className="space-y-2">
                   <p className="text-xs text-ae-muted mb-2">
                     Enter email to unlock spec file ({tool.demoFileSize || 'Unknown'}).
                   </p>
                   <div className="relative">
                     <Mail className="absolute left-3 top-2.5 w-4 h-4 text-ae-muted/50" />
                     <input 
                       type="email" 
                       required
                       placeholder="name@company.com"
                       className="w-full bg-black/20 border border-white/10 rounded text-sm py-2 pl-9 pr-3 text-ae-light focus:border-ae-accent focus:ring-1 focus:ring-ae-accent outline-none"
                       value={email}
                       onChange={(e) => setEmail(e.target.value)}
                     />
                   </div>
                   <Button 
                     size="sm" 
                     className="w-full text-xs" 
                     disabled={isSubmittingEmail}
                   >
                     {isSubmittingEmail ? 'Unlocking...' : 'Unlock Download'}
                   </Button>
                 </form>
               ) : (
                 <div className="animate-in fade-in slide-in-from-bottom-2">
                   <p className="text-xs text-green-400 mb-2 flex items-center gap-1">
                     <Check className="w-3 h-3" /> Unlocked
                   </p>
                   <Button 
                     variant="outline" 
                     size="sm" 
                     onClick={handleDownload}
                     disabled={isDownloading}
                     className="w-full text-xs gap-2 border-ae-accent text-ae-accent hover:bg-ae-accent hover:text-ae-darker"
                   >
                     {isDownloading ? (
                       <span className="animate-pulse">Downloading...</span>
                     ) : (
                       <>
                         <Download className="w-4 h-4" /> Download .MD File
                       </>
                     )}
                   </Button>
                 </div>
               )}
             </div>

             {/* System Prompt Peek */}
             <div className="mt-4 pt-4 border-t border-white/10">
               <button 
                 onClick={() => setShowSystemPrompt(!showSystemPrompt)}
                 className="flex items-center justify-between w-full text-xs text-ae-muted hover:text-ae-accent transition-colors mb-2"
               >
                 <span className="flex items-center gap-2 font-bold uppercase"><Cpu className="w-3 h-3" /> System Intelligence</span>
                 {showSystemPrompt ? <EyeOff className="w-3 h-3" /> : <Eye className="w-3 h-3" />}
               </button>
               
               {showSystemPrompt && (
                 <div className="p-3 bg-black/40 rounded border border-ae-accent/20 text-xs text-ae-muted font-mono leading-relaxed animate-in slide-in-from-top-2 duration-200">
                   <span className="text-ae-accent block mb-1">// SYSTEM INSTRUCTION</span>
                   {tool.systemPromptTeaser}
                 </div>
               )}
             </div>
          </div>

          {/* Right Panel: Output */}
          <div className="w-full md:flex-grow p-4 md:p-6 flex flex-col bg-gradient-to-br from-ae-dark to-ae-darker min-h-[400px]">
            
            {/* Input Display */}
            <div className="mb-6">
               <label className="text-xs font-bold text-ae-muted uppercase mb-2 block">User Input</label>
               <div className={`w-full p-4 rounded-lg border transition-all min-h-[60px] md:min-h-[80px] text-sm font-mono ${input ? 'bg-ae-card border-ae-accent/30 text-ae-light' : 'bg-black/20 border-white/5 text-ae-muted italic'}`}>
                 {input || "Select a scenario from the list to begin..."}
               </div>
            </div>

            {/* Output Display */}
            <div className="flex-grow flex flex-col min-h-[300px] relative">
               <div className="flex justify-between items-center mb-2">
                 <label className="text-xs font-bold text-ae-accent uppercase flex items-center gap-2">
                   {loading ? (
                     <>
                       <span className="block w-2 h-2 bg-ae-accent rounded-full animate-ping"></span>
                       Analyzing...
                     </>
                   ) : (
                     'Model Output'
                   )}
                 </label>
                 
                 {response && !loading && (
                   <button 
                     onClick={copyPrompt} 
                     className="text-xs flex items-center gap-1 text-ae-muted hover:text-white transition-colors bg-white/5 hover:bg-ae-accent/10 px-3 py-1.5 rounded border border-white/10 hover:border-ae-accent/30"
                   >
                     {copied ? <Check className="w-3 h-3 text-green-400" /> : <Copy className="w-3 h-3" />}
                     <span className="hidden sm:inline">{copied ? 'Copied Context' : 'Copy Context'}</span>
                   </button>
                 )}
               </div>

               <div className={`flex-grow rounded-xl border p-4 md:p-6 text-sm leading-relaxed font-mono whitespace-pre-wrap overflow-y-auto transition-all duration-500 relative ${
                 response 
                   ? 'bg-ae-card border-ae-accent/20 text-ae-light shadow-[0_0_30px_-10px_rgba(245,158,11,0.1)]' 
                   : 'bg-black/20 border-white/5 text-ae-muted/30 flex items-center justify-center'
               }`}>
                 {loading ? (
                   <div className="space-y-3 w-full max-w-md opacity-50">
                     <div className="flex items-center gap-2 mb-4">
                        <div className="w-4 h-4 border-2 border-ae-accent border-t-transparent rounded-full animate-spin"></div>
                        <span className="text-xs font-sans">Processing logic...</span>
                     </div>
                     <div className="h-2 bg-ae-accent/50 rounded w-3/4 animate-pulse"></div>
                     <div className="h-2 bg-ae-accent/30 rounded w-full animate-pulse delay-75"></div>
                     <div className="h-2 bg-ae-accent/40 rounded w-5/6 animate-pulse delay-150"></div>
                   </div>
                 ) : (
                   <>
                     {response || (
                       <div className="text-center">
                         <Sparkles className="w-8 h-8 mx-auto mb-3 opacity-20" />
                         <p>AI output will appear here</p>
                       </div>
                     )}
                     {response && (
                       <div className="absolute top-4 right-4 opacity-20 hover:opacity-100 transition-opacity">
                         <span className="text-[10px] border border-white/30 px-2 py-1 rounded-full uppercase tracking-widest">Simulation</span>
                       </div>
                     )}
                   </>
                 )}
               </div>
            </div>

            {/* External Link Hint */}
            {response && (
              <div className="mt-4 pt-4 border-t border-white/5 animate-in slide-in-from-bottom-2 fade-in duration-500">
                <p className="text-xs text-ae-muted flex items-center gap-2 bg-ae-accent/5 p-3 rounded border border-ae-accent/10">
                  <ExternalLink className="w-3 h-3 text-ae-accent flex-shrink-0" />
                  <span className="flex-grow">
                    <strong>Like this result?</strong> Copy the prompt context above to test it.
                  </span>
                </p>
              </div>
            )}

          </div>
        </div>

        {/* Footer CTA */}
        <div className="p-4 border-t border-white/10 bg-ae-darker flex justify-between items-center flex-shrink-0">
          <div className="text-xs text-ae-muted hidden sm:block">
            * Simulation uses pre-validated outputs.
          </div>
          <Button size="sm" className="ml-auto font-bold shadow-[0_0_15px_-5px_rgba(245,158,11,0.4)]">
            Purchase Full Tool
          </Button>
        </div>
      </div>
    </div>
  );
};

// Simple arrow icon helper
const ArrowIcon = ({ className }: { className?: string }) => (
  <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
  </svg>
);

export default TeaserModal;
